GHA: artifactory publish workflow: set artifactory key from secrets (#2375)
## Summary
1. Why: artifactory publishing is still broken, due to invalid username
2. What: username is required and must be a valid one: use 

## Expected Behavior
- artifactory publishing is working

## Actual Behavior
- artifactory publishing is [broken](https://github.com/linkedin/cruise-control/actions/runs/26468260356)

```
Execution failed for task ':artifactoryDeploy'.
> java.io.IOException: JFrog service failed. Received 401: {
    "errors" : [ {
      "status" : 401,
      "message" : "Unauthorized"
    } ]
  }
```

## Steps to Reproduce
https://github.com/linkedin/cruise-control/actions/runs/26468260356

## Known Workarounds
- n/a

## Categorization
- [ ] documentation
- [ ] bugfix
- [ ] new feature
- [ ] refactor
- [x] security/CVE
- [ ] other

This PR resolves #<Replace-Me-With-The-Issue-Number-Addressed-By-This-PR> if any.